version: "3.9"

services:
  db:
    container_name: database_container
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mynetwork
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    container_name: dormy_api_container
    build:
      context: ./thue
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - mynetwork

  web:
    container_name: dormy_web_container
    build:
      context: ./thuefe
      dockerfile: Dockerfile
      args:
        VITE_BASE_API_URL: http://100.26.108.191:5000/api/
    ports:
      - 5174:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - react_node_modules:/app/node_modules
    networks:
      - mynetwork
    depends_on:
      - api

volumes:
  pg_data:
  react_node_modules:
  pgadmin_data:

networks:
  mynetwork:
    driver: bridge
